# Generated by Django 4.2.6 on 2023-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.TextField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
